"""Agregar coordinador a orden de compra

Revision ID: 0e4cc54bcb84
Revises: 9e8dcb0df2d7
Create Date: 2026-01-24 12:49:21.670879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4cc54bcb84'
down_revision = '9e8dcb0df2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinator', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('coordinator')

    # ### end Alembic commands ###
