"""allow null po in receipts

Revision ID: 1d5529871cb9
Revises: 0e4cc54bcb84
Create Date: 2026-01-28 12:30:34.767059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5529871cb9'
down_revision = '0e4cc54bcb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.alter_column('purchase_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_product_receipts_provider_id_providers'), 'providers', ['provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_receipts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_receipts_provider_id_providers'), type_='foreignkey')
        batch_op.alter_column('purchase_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###
