"""add document_class to purchase order

Revision ID: 6e822fdf5191
Revises: 1d5529871cb9
Create Date: 2026-02-04 09:58:49.005606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e822fdf5191'
down_revision = '1d5529871cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_class', sa.String(length=50), server_default='Factura', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('document_class')

    # ### end Alembic commands ###
