"""Inicializando BD con snapshots

Revision ID: 8887ade01c40
Revises: 
Create Date: 2025-12-18 10:48:50.111721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8887ade01c40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_account_types_name'), ['name'])

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bank_accounts_account_number'), ['account_number'])

    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_banks_name'), ['name'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categories_name'), ['name'])

    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_cost_centers_code'), ['code'])

    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_document_types_name'), ['name'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employees_document_number'), ['document_number'])

    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_expense_types_name'), ['name'])

    with op.batch_alter_table('income_types', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_income_types_name'), ['name'])

    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_order_statuses_name'), ['name'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_permissions_name'), ['name'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_products_sku'), ['sku'])
        batch_op.create_foreign_key(batch_op.f('fk_products_unit_measure_id_unit_measure'), 'unit_measure', ['unit_measure_id'], ['id'])
        batch_op.drop_column('unit_of_measure')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_providers_ruc'), ['ruc'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    with op.batch_alter_table('stock_transfer_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name_snapshot', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('product_sku_snapshot', sa.String(length=100), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ubigeos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ubigeos_ubigeo_inei'), ['ubigeo_inei'])

    with op.batch_alter_table('unit_measure', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_unit_measure_sunat_code'), ['sunat_code'])

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_warehouses_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_warehouses_name'), type_='unique')

    with op.batch_alter_table('unit_measure', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_unit_measure_sunat_code'), type_='unique')

    with op.batch_alter_table('ubigeos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ubigeos_ubigeo_inei'), type_='unique')

    with op.batch_alter_table('stock_transfer_items', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('product_sku_snapshot')
        batch_op.drop_column('product_name_snapshot')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_providers_ruc'), type_='unique')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_measure', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_products_unit_measure_id_unit_measure'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_products_sku'), type_='unique')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_permissions_name'), type_='unique')

    with op.batch_alter_table('order_statuses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_order_statuses_name'), type_='unique')

    with op.batch_alter_table('income_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_income_types_name'), type_='unique')

    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_expense_types_name'), type_='unique')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_document_number'), type_='unique')

    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_types_name'), type_='unique')

    with op.batch_alter_table('cost_centers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_cost_centers_code'), type_='unique')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categories_name'), type_='unique')

    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_banks_name'), type_='unique')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bank_accounts_account_number'), type_='unique')

    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_account_types_name'), type_='unique')

    # ### end Alembic commands ###
