"""add status to gre

Revision ID: 9e8dcb0df2d7
Revises: b0c422384c6f
Create Date: 2026-01-21 15:53:40.769357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8dcb0df2d7'
down_revision = 'b0c422384c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gre', schema=None) as batch_op:
        # AGREGAMOS server_default='emitido' AQUÍ ABAJO:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='emitido'))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('order_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'OC'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('order_type',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'OC'"))

    with op.batch_alter_table('gre', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
