"""empty message

Revision ID: b0c422384c6f
Revises: 8887ade01c40
Create Date: 2025-12-18 15:52:46.501612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c422384c6f'
down_revision = '8887ade01c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xml_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gre', schema=None) as batch_op:
        batch_op.drop_column('xml_hash')

    # ### end Alembic commands ###
