"""Add TreasuryRenderDetail model and update TreasuryAllocationRender

Revision ID: b5aa1dc48376
Revises: d87d0d83769e
Create Date: 2026-02-13 16:44:38.104502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5aa1dc48376'
down_revision = 'd87d0d83769e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_render_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('render_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('invoice_series', sa.String(length=20), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['render_id'], ['treasury_allocation_renders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treasury_render_details')
    # ### end Alembic commands ###
