"""Add treasury status and cost_center_id

Revision ID: d87d0d83769e
Revises: 
Create Date: 2026-02-11 12:57:02.552289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87d0d83769e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set default value for existing NULL unit_price records before altering column to non-nullable
    op.execute("UPDATE product_receipt_items SET unit_price = 0.00 WHERE unit_price IS NULL")
    with op.batch_alter_table('product_receipt_items', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('treasury_allocation_renders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_center_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_treasury_allocation_renders_cost_center_id_cost_centers'), 'cost_centers', ['cost_center_id'], ['id'])

    with op.batch_alter_table('treasury_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='Pendiente'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treasury_transactions', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('treasury_allocation_renders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_treasury_allocation_renders_cost_center_id_cost_centers'), type_='foreignkey')
        batch_op.drop_column('cost_center_id')

    with op.batch_alter_table('product_receipt_items', schema=None) as batch_op:
        batch_op.alter_column('unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
